[package]
name = "ultvox"
version = "0.4.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bevy = { version = "0.19.0", default-features = false, features = ["default_app", "tonemapping_luts", "bevy_pbr", "bevy_asset", "bevy_core_pipeline", "bevy_render", "bevy_scene", "bevy_sprite", "bevy_text", "bevy_winit", "png", "x11"] }
bevy_egui = { version = "0.40.1", default-features = false, features = ["bevy_ui", "default_fonts", ] }
serde = "1.0.228"
ron = "0.12.2"

rustmatica = "0.5.2"
mcdata = { version = "0.4.0", features = ["latest", "block-states"] }

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
